GET http://localhost:3001/episode HTTP/1.1
###





GET http://localhost:3001/character HTTP/1.1
###
GET http://localhost:3001/character/118 HTTP/1.1
###
GET http://localhost:3001/character/1 HTTP/1.1
###
GET http://localhost:3001/character/830af1ac-9c3e-4e15-f1d-e1238e18becc HTTP/1.1
###
GET http://localhost:3001/character?name=evil HTTP/1.1
###
POST http://localhost:3001/character HTTP/1.1
content-type: application/json

{
    "name": "morty dito",
    "status": "Alive",
    "location": "pokemon go",
    "epId": "2000",
    "image": "https://rickandmortyapi.com/api/character/avatar/55.jpeg"

}